CREATE TABLE movies
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           varchar(255) NOT NULL,
    genre           varchar(255) NOT NULL,
    rating          float NOT NULL,
    release_date    date NOT NULL
)