CREATE TABLE movies (
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    year VARCHAR(255) NOT NULL,
    rated VARCHAR(255) NOT NULL,
    released VARCHAR(255),
    runtime VARCHAR(255),
    genre VARCHAR(255),
    director VARCHAR(255),
    writer VARCHAR(255),
    actors VARCHAR(255),
    plot VARCHAR(1000),
    language VARCHAR(255),
    country VARCHAR(255),
    awards VARCHAR(255),
    poster VARCHAR(255),
    metascore VARCHAR(255),
    imdb_rating VARCHAR(255),
    imdb_votes VARCHAR(255),
    imdb_id VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    dvd VARCHAR(255),
    box_office VARCHAR(255),
    production VARCHAR(255),
    website VARCHAR(255),
    response VARCHAR(255) NOT NULL
);

insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Tim Robbins, Morgan Freeman, Bob Gunton', 'Nominated for 7 Oscars. 21 wins & 42 nominations total', '$28,767,189', 'United States', 'Frank Darabont', '15 Aug 2008', 'Drama', 22, 'tt0111161', '9.3', '2,824,159', 'English', '82', 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.', 'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg', 'N/A', 'R', '14 Oct 1994', 'True', '142 min', 'The Shawshank Redemption', 'movie', 'N/A', 'Stephen King, Frank Darabont', '1994');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Marlon Brando, Al Pacino, James Caan', 'Won 3 Oscars. 30 wins & 31 nominations total', '$136,381,073', 'United States', 'Francis Ford Coppola', '01 Aug 2013', 'Crime, Drama', 23, 'tt0068646', '9.2', '1,970,343', 'English, Italian, Latin', '100', 'Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'N/A', 'R', '24 Mar 1972', 'True', '175 min', 'The Godfather', 'movie', 'N/A', 'Mario Puzo, Francis Ford Coppola', '1972');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Al Pacino, Robert De Niro, Robert Duvall', 'Won 6 Oscars. 17 wins & 21 nominations total', '$47,834,595', 'United States', 'Francis Ford Coppola', '15 Sep 2012', 'Crime, Drama', 24, 'tt0071562', '9.0', '1,337,309', 'English, Italian, Spanish, Latin, Sicilian', '90', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'N/A', 'R', '18 Dec 1974', 'True', '202 min', 'The Godfather Part II', 'movie', 'N/A', 'Francis Ford Coppola, Mario Puzo', '1974');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Christian Bale, Heath Ledger, Aaron Eckhart', 'Won 2 Oscars. 162 wins & 164 nominations total', '$534,987,076', 'United States, United Kingdom', 'Christopher Nolan', '14 Jun 2010', 'Action, Crime, Drama', 25, 'tt0468569', '9.0', '2,808,696', 'English, Mandarin', '84', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 'N/A', 'PG-13', '18 Jul 2008', 'True', '152 min', 'The Dark Knight', 'movie', 'N/A', 'Jonathan Nolan, Christopher Nolan, David S. Goyer', '2008');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Brad Pitt, Edward Norton, Meat Loaf', 'Nominated for 1 Oscar. 12 wins & 38 nominations total', '$37,030,102', 'Germany, United States', 'David Fincher', '19 Nov 2014', 'Drama', 26, 'tt0137523', '8.8', '2,259,473', 'English', '67', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg', 'N/A', 'R', '15 Oct 1999', 'True', '139 min', 'Fight Club', 'movie', 'N/A', 'Chuck Palahniuk, Jim Uhls', '1999');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Tom Hanks, Robin Wright, Gary Sinise', 'Won 6 Oscars. 50 wins & 74 nominations total', '$330,455,270', 'United States', 'Robert Zemeckis', '01 Aug 2013', 'Drama, Romance', 27, 'tt0109830', '8.8', '2,203,270', 'English', '82', 'The history of the United States from the 1950s to the ''70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'N/A', 'PG-13', '06 Jul 1994', 'True', '142 min', 'Forrest Gump', 'movie', 'N/A', 'Winston Groom, Eric Roth', '1994');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Elijah Wood, Viggo Mortensen, Ian McKellen', 'Won 11 Oscars. 215 wins & 124 nominations total', '$379,427,292', 'New Zealand, United States', 'Peter Jackson', '06 Apr 2010', 'Action, Adventure, Drama', 28, 'tt0167260', '9.0', '1,935,582', 'English, Quenya, Old English, Sindarin', '94', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'N/A', 'PG-13', '17 Dec 2003', 'True', '201 min', 'The Lord of the Rings: The Return of the King', 'movie', 'N/A', 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens', '2003');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Clint Eastwood, Eli Wallach, Lee Van Cleef', '2 wins & 5 nominations', '$25,100,000', 'Italy, Spain, West Germany', 'Sergio Leone', '27 Aug 2015', 'Adventure, Western', 29, 'tt0060196', '8.8', '796,239', 'Italian', '90', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 'https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg', 'N/A', 'Approved', '29 Dec 1967', 'True', '178 min', 'The Good, the Bad and the Ugly', 'movie', 'N/A', 'Luciano Vincenzoni, Sergio Leone, Agenore Incrocci', '1966');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Elijah Wood, Ian McKellen, Orlando Bloom', 'Won 4 Oscars. 125 wins & 127 nominations total', '$316,115,420', 'New Zealand, United States', 'Peter Jackson', '28 Jun 2011', 'Action, Adventure, Drama', 30, 'tt0120737', '8.8', '1,962,690', 'English, Sindarin', '92', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg', 'N/A', 'PG-13', '19 Dec 2001', 'True', '178 min', 'The Lord of the Rings: The Fellowship of the Ring', 'movie', 'N/A', 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens', '2001');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'Won 4 Oscars. 42 wins & 52 nominations total', '$172,076,928', 'United States, Australia', 'Lana Wachowski, Lilly Wachowski', '01 Jan 2009', 'Action, Sci-Fi', 31, 'tt0133093', '8.7', '2,007,561', 'English', '73', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'N/A', 'R', '31 Mar 1999', 'True', '136 min', 'The Matrix', 'movie', 'N/A', 'Lilly Wachowski, Lana Wachowski', '1999');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Caglar Ertugrul, Ufuk Bayraktar, Ahu Türkpençe', '2 wins & 2 nominations', 'N/A', 'Turkey', 'Alper Caglar', 'N/A', 'Action, Drama, War', 32, 'tt5813916', '8.2', '109,760', 'Turkish', 'N/A', 'In a desolate war zone where screams of the innocent echo, seven Maroon Berets will dance with death on the very line between disaster and valor.', 'https://m.media-amazon.com/images/M/MV5BN2I2NGMzMTItNWI4YS00MWRiLTliZTEtNzhjODE3NDcyZjQwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'N/A', 'N/A', '04 Nov 2016', 'True', '135 min', 'The Mountain II', 'movie', 'N/A', 'Alper Caglar', '2016');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Jack Nicholson, Louise Fletcher, Michael Berryman', 'Won 5 Oscars. 38 wins & 15 nominations total', '$108,981,275', 'United States', 'Milos Forman', '30 Nov 2016', 'Drama', 33, 'tt0073486', '8.7', '1,051,325', 'English', '84', 'In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.', 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'N/A', 'R', '19 Nov 1975', 'True', '133 min', 'One Flew Over the Cuckoo''s Nest', 'movie', 'N/A', 'Lawrence Hauben, Bo Goldman, Ken Kesey', '1975');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Tatsuya Nakadai, Akira Ishihama, Shima Iwashita', '9 wins & 3 nominations', 'N/A', 'Japan', 'Masaki Kobayashi', '11 Mar 2017', 'Action, Drama, Mystery', 34, 'tt0056058', '8.6', '64,951', 'Japanese', '85', 'When a ronin requesting seppuku at a feudal lord''s palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan''s integrity.', 'https://m.media-amazon.com/images/M/MV5BYjBmYTQ1NjItZWU5MS00YjI0LTg2OTYtYmFkN2JkMmNiNWVkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg', 'N/A', 'Not Rated', '04 Aug 1964', 'True', '133 min', 'Harakiri', 'movie', 'N/A', 'Yasuhiko Takiguchi, Shinobu Hashimoto', '1962');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Joaquin Phoenix, Robert De Niro, Zazie Beetz', 'Won 2 Oscars. 121 wins & 239 nominations total', '$335,477,657', 'United States, Canada', 'Todd Phillips', '03 Oct 2019', 'Crime, Drama, Thriller', 35, 'tt7286456', '8.4', '1,424,443', 'English, German', '59', 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.', 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'N/A', 'R', '04 Oct 2019', 'True', '122 min', 'Joker', 'movie', 'N/A', 'Todd Phillips, Scott Silver, Bob Kane', '2019');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Miles Teller, J.K. Simmons, Melissa Benoist', 'Won 3 Oscars. 98 wins & 144 nominations total', '$13,092,000', 'United States', 'Damien Chazelle', '08 Sep 2016', 'Drama, Music', 36, 'tt2582802', '8.5', '942,571', 'English', '89', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student''s potential.', 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'N/A', 'R', '15 Oct 2014', 'True', '106 min', 'Whiplash', 'movie', 'N/A', 'Damien Chazelle', '2014');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Robert Downey Jr., Chris Hemsworth, Mark Ruffalo', 'Nominated for 1 Oscar. 46 wins & 80 nominations total', '$678,815,482', 'United States', 'Anthony Russo, Joe Russo', '31 Jul 2018', 'Action, Adventure, Sci-Fi', 37, 'tt4154756', '8.4', '1,170,647', 'English', '68', 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.', 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg', 'N/A', 'PG-13', '27 Apr 2018', 'True', '149 min', 'Avengers: Infinity War', 'movie', 'N/A', 'Christopher Markus, Stephen McFeely, Stan Lee', '2018');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Ben Burtt, Elissa Knight, Jeff Garlin', 'Won 1 Oscar. 96 wins & 95 nominations total', '$223,808,164', 'United States, Japan', 'Andrew Stanton', '01 Jan 2014', 'Animation, Adventure, Family', 38, 'tt0910970', '8.4', '1,171,246', 'English', '95', 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.', 'https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg', 'N/A', 'G', '27 Jun 2008', 'True', '98 min', 'WALL·E', 'movie', 'N/A', 'Andrew Stanton, Pete Docter, Jim Reardon', '2008');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('François Cluzet, Omar Sy, Anne Le Ny', 'Nominated for 1 BAFTA Award38 wins & 40 nominations total', '$10,198,820', 'France', 'Olivier Nakache, Éric Toledano', '05 Mar 2013', 'Biography, Comedy, Drama', 39, 'tt1675434', '8.5', '908,942', 'French, English', '57', 'After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.', 'https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX300.jpg', 'N/A', 'R', '02 Nov 2011', 'True', '112 min', 'The Intouchables', 'movie', 'N/A', 'Olivier Nakache, Éric Toledano, Philippe Pozzo di Borgo', '2011');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Adrien Brody, Thomas Kretschmann, Frank Finlay', 'Won 3 Oscars. 57 wins & 74 nominations total', '$32,572,577', 'France, Poland, Germany, United Kingdom, United States', 'Roman Polanski', '19 Apr 2016', 'Biography, Drama, Music', 40, 'tt0253474', '8.5', '887,926', 'English, German, Russian', '85', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.', 'https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'N/A', 'R', '28 Mar 2003', 'True', '150 min', 'The Pianist', 'movie', 'N/A', 'Ronald Harwood, Wladyslaw Szpilman', '2002');
insert into "movies" ("actors", "awards", "box_office", "country", "director", "dvd", "genre", "id", "imdb_id", "imdb_rating", "imdb_votes", "language", "metascore", "plot", "poster", "production", "rated", "released", "response", "runtime", "title", "type", "website", "writer", "year") values ('Leonardo DiCaprio, Matt Damon, Jack Nicholson', 'Won 4 Oscars. 98 wins & 141 nominations total', '$132,399,394', 'United States, Hong Kong', 'Martin Scorsese', '24 Oct 2008', 'Crime, Drama, Thriller', 41, 'tt0407887', '8.5', '1,393,861', 'English, Cantonese', '85', 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg', 'N/A', 'R', '06 Oct 2006', 'True', '151 min', 'The Departed', 'movie', 'N/A', 'William Monahan, Alan Mak, Felix Chong', '2006');