INSERT INTO songs (name, singer, genre, spotify_id)
VALUES
    ('Shape of You', 'Ed Sheeran', 'Pop', '7qiZfU4dY1lWllzX7mPBI3'),
    ('Blinding Lights', 'The Weeknd', 'R&B', '0VjIjW4GlUZAMYd2vXMi3b'),
    ('Dance Monkey', 'Tones and I', 'Pop', '2XU0oxnq2qxCpomAAuJY8K'),
    ('Someone You Loved', 'Lewis Capaldi', 'Pop', '7qEHsqek33rTcFNT9PFqLf'),
    ('Uptown Funk', 'Mark Ronson ft. Bruno Mars', 'Funk', '4dW2ft2qKOULK0ekujxUq7'),
    ('Watermelon Sugar', 'Harry Styles', 'Pop', '6UelLqGlWMcVH1E5c4H7lY'),
    ('Sicko Mode', 'Travis Scott', 'Hip Hop', '2xLMifQCjDGFmkHkpNLD9h'),
    ('Savage Love', 'Jawsh 685 & Jason Derulo', 'Pop', '6YoE8zXRkktbtvp072Awer'),
    ('Levitating', 'Dua Lipa', 'Pop', '39LLxExYz6ewLAcYrzQQyP'),
    ('WAP', 'Cardi B ft. Megan Thee Stallion', 'Hip Hop', '0K7IDAcsH4ade0oI0tbtfk'),
    ('Rockstar', 'Post Malone ft. 21 Savage', 'Hip Hop', '17u2WZq0EgeX5Ra3c1v6n9'),
    ('Physical', 'Dua Lipa', 'Pop', '3AzjcOeAmA57TIOr9zF1ZW'),
    ('Circles', 'Post Malone', 'Pop', '21jGcNKet2qwijlDFuPiPb'),
    ('Dynamite', 'BTS', 'Pop', '5QDLhrAOJJdNAmCTJ8xMyW'),
    ('Say So', 'Doja Cat', 'Pop', '3Dv1eDb0MEgF93GpLXlucZ'),
    ('Rain On Me', 'Lady Gaga ft. Ariana Grande', 'Pop', '7ju97lgwC2rKQ6wwsf9no9'),
    ('Stressed Out', 'Twenty One Pilots', 'Pop', '3CRDbSIZ4r5MsZ0YwxuEkn'),
    ('Cry Baby', 'Megan Thee Stallion ft. DaBaby', 'Hip Hop', '1NkUJt3FryO6MDLzSMfYJv'),
    ('Senorita', 'Shawn Mendes, Camila Cabello', 'Pop', '6v3KW9xbzN5yKLt9YKDYA2'),
    ('Laugh Now Cry Later', 'Drake ft. Lil Durk', 'Hip Hop', '7IRMf1AY2N6rQp3ljGhxDf'),
    ('Bad Guy', 'Billie Eilish', 'Pop', '2Fxmhks0bxGSBdJ92vM42m'),
    ('Mood', '24kGoldn ft. Iann Dior', 'Hip Hop', '3FJ7DtxXvO6NnLm1zjf7uQ'),
    ('Wrecking Ball', 'Miley Cyrus', 'Pop', '2vwlzO0Qp8kfEtzTsCXfyE'),
    ('Old Town Road', 'Lil Nas X ft. Billy Ray Cyrus', 'Country', '4jEuRpBmGDFulfq13NlHb6'),
    ('Sucker', 'Jonas Brothers', 'Pop', '22vgEDb5hykfaTwLuskFGD'),
    ('Hotline Bling', 'Drake', 'Hip Hop', '0wwPcA6wtMf6HUMpIRdeP7'),
    ('Despacito', 'Luis Fonsi ft. Daddy Yankee', 'Latin', '5oO6i1qhCc6VXvHMvoPFpi'),
    ('Havana', 'Camila Cabello ft. Young Thug', 'Pop', '0cSrrnYbI0DPaTHZQObpB8'),
    ('All About That Bass', 'Meghan Trainor', 'Pop', '5jE48hhRu8E6zBDPRSkEq7'),
    ('Happier', 'Marshmello ft. Bastille', 'Pop', '2gq5d9v4naGWjQsv80r145');

